[tool.poetry]
name = "homework-21-2"
version = "0.1.0"
description = ""
authors = ["Vladislav Zorin <zorin.3v6@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
